spring:
  config:
    name: journal
  datasource:
    url: jdbc:postgresql://localhost:5432/practica4
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
server:
  port: 8080
  servlet:
    session:
      timeout: 15m
      persistent: true
      maxInactiveInterval: 180